import { Router } from "express";
import * as C from "../controllers/ClientController.js";
import { authenticate, authorize } from "../middlewares/auth.js";
const router = Router();
router.use(authenticate);
router.get("/", C.list);
router.get("/cedula/:cedula", C.byCedula);
router.get("/:id", C.get);
router.post("/", authorize("Administrador", "Entrenador"), C.create);
router.put("/:id", authorize("Administrador", "Entrenador"), C.update);
router.patch("/:id/estado", authorize("Administrador"), C.setStatus);
export default router;
