import { Router } from "express";
import * as C from "../controllers/TrainerController.js";
import { authenticate, authorize } from "../middlewares/auth.js";
const router = Router();
router.use(authenticate);
router.get("/", C.list);
router.get("/sesiones", C.sessions);
router.patch("/sesiones/:id/estado", authorize("Entrenador", "Administrador"), C.setSessionStatus);
router.post("/", authorize("Administrador"), C.create);
router.put("/:id", authorize("Administrador"), C.update);
router.patch("/:id/estado", authorize("Administrador"), C.setStatus);
router.post("/sesiones", authorize("Entrenador", "Administrador"), C.schedule);
export default router;
