create extension if not exists btree_gist with schema extensions;

create table public.roles (
  id smallint generated by default as identity primary key,
  nombre text not null unique,
  constraint roles_nombre_valido check (nombre in ('Administrador', 'Entrenador'))
);

create table public.usuarios (
  id bigint generated by default as identity primary key,
  cedula text not null unique,
  nombre_completo text not null,
  email text not null,
  password_hash text not null,
  rol_id smallint not null references public.roles(id),
  activo boolean not null default true,
  es_administrador_principal boolean not null default false,
  fecha_creacion timestamptz not null default now()
);

create unique index usuarios_email_unico_idx on public.usuarios (lower(email));
create index usuarios_rol_id_idx on public.usuarios (rol_id);

create table public.entrenadores (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null unique references public.usuarios(id),
  horario_inicio time not null,
  horario_fin time not null,
  constraint entrenadores_horario_valido check (horario_inicio < horario_fin)
);

create table public.horarios_entrenadores (
  id bigint generated by default as identity primary key,
  entrenador_id bigint not null references public.entrenadores(id),
  dia_semana smallint not null,
  hora_inicio time not null,
  hora_fin time not null,
  constraint horarios_dia_valido check (dia_semana between 1 and 7),
  constraint horarios_rango_valido check (hora_inicio < hora_fin),
  constraint horarios_entrenador_dia_unico unique (entrenador_id, dia_semana)
);

create index horarios_entrenadores_entrenador_id_idx on public.horarios_entrenadores (entrenador_id);

create table public.clientes (
  id bigint generated by default as identity primary key,
  usuario_id bigint unique references public.usuarios(id),
  cedula text not null unique,
  nombre_completo text not null,
  edad smallint not null,
  lesiones_enfermedades text,
  plan_adquirido text not null,
  entrenador_asignado_id bigint references public.entrenadores(id),
  activo boolean not null default true,
  constraint clientes_edad_valida check (edad between 1 and 120)
);

create index clientes_entrenador_asignado_id_idx on public.clientes (entrenador_asignado_id);
create index clientes_activos_nombre_idx on public.clientes (nombre_completo) where activo;

create table public.mediciones (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id),
  entrenador_id bigint not null references public.entrenadores(id),
  fecha_medicion date not null,
  estatura numeric(6,2),
  peso numeric(6,2),
  masa_muscular numeric(6,2),
  porcentaje_grasa numeric(5,2),
  cintura numeric(6,2),
  cadera numeric(6,2),
  brazo_izquierdo numeric(6,2),
  brazo_derecho numeric(6,2),
  pierna_izquierda numeric(6,2),
  pierna_derecha numeric(6,2),
  pantorrilla_izquierda numeric(6,2),
  pantorrilla_derecha numeric(6,2),
  pectoral numeric(6,2),
  espalda numeric(6,2),
  constraint mediciones_valores_no_negativos check (
    coalesce(estatura, 0) >= 0 and coalesce(peso, 0) >= 0 and coalesce(masa_muscular, 0) >= 0
    and coalesce(porcentaje_grasa, 0) >= 0 and coalesce(cintura, 0) >= 0 and coalesce(cadera, 0) >= 0
    and coalesce(brazo_izquierdo, 0) >= 0 and coalesce(brazo_derecho, 0) >= 0
    and coalesce(pierna_izquierda, 0) >= 0 and coalesce(pierna_derecha, 0) >= 0
    and coalesce(pantorrilla_izquierda, 0) >= 0 and coalesce(pantorrilla_derecha, 0) >= 0
    and coalesce(pectoral, 0) >= 0 and coalesce(espalda, 0) >= 0
  )
);

create index mediciones_cliente_fecha_idx on public.mediciones (cliente_id, fecha_medicion desc);
create index mediciones_entrenador_id_idx on public.mediciones (entrenador_id);

create table public.sesiones_personalizadas (
  id bigint generated by default as identity primary key,
  entrenador_id bigint not null references public.entrenadores(id),
  cliente_id bigint not null references public.clientes(id),
  fecha_hora_inicio timestamptz not null,
  fecha_hora_fin timestamptz not null,
  constraint sesiones_rango_valido check (fecha_hora_inicio < fecha_hora_fin),
  constraint sesiones_entrenador_sin_solapes exclude using gist (
    entrenador_id with =,
    tstzrange(fecha_hora_inicio, fecha_hora_fin, '[)') with &&
  )
);

create index sesiones_cliente_id_idx on public.sesiones_personalizadas (cliente_id);
create index sesiones_entrenador_fecha_idx on public.sesiones_personalizadas (entrenador_id, fecha_hora_inicio);

alter table public.roles enable row level security;
alter table public.usuarios enable row level security;
alter table public.entrenadores enable row level security;
alter table public.horarios_entrenadores enable row level security;
alter table public.clientes enable row level security;
alter table public.mediciones enable row level security;
alter table public.sesiones_personalizadas enable row level security;

revoke all on table public.roles, public.usuarios, public.entrenadores, public.horarios_entrenadores,
  public.clientes, public.mediciones, public.sesiones_personalizadas from anon, authenticated;
